default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: domus_development

test:
  <<: *default
  database: domus_test

production:
  <<: *default
  database: domus_production
